name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.fulfillment-dev.click
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      -
        name: Build the Docker image
        run: docker build -t harbor.fulfillment-dev.click/test --tag ${{ steps.date.outputs.date }} .
      -
        name: Docker Push
        run: docker push harbor.fulfillment-dev.click/test:${{ steps.date.outputs.date }}:latest
