name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  docker:
    name: Test docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Set up Docker build environment - QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker build environment - BUILDX
        uses: docker/setup-buildx-action@v1

      - name: Test docker image build - argocd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          no-cache: true
          push: false
          tags: argocd:build-only
